// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhfP-WakfgPwttHN3WLKMu2L3_Tt5B-Sc',
    appId: '1:677990370488:web:1f6136f65efe340d30b84d',
    messagingSenderId: '677990370488',
    projectId: 'coffee-app-589b0',
    authDomain: 'coffee-app-589b0.firebaseapp.com',
    storageBucket: 'coffee-app-589b0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-IhMMLf4VGm6CgvCsDuYmQjFVSubPoRY',
    appId: '1:677990370488:android:3de5e29dfa03b5d730b84d',
    messagingSenderId: '677990370488',
    projectId: 'coffee-app-589b0',
    storageBucket: 'coffee-app-589b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy5c_ibXGLf_X5dTYfjec-LhMoQecCuwg',
    appId: '1:677990370488:ios:c1d5eec707700a2130b84d',
    messagingSenderId: '677990370488',
    projectId: 'coffee-app-589b0',
    storageBucket: 'coffee-app-589b0.appspot.com',
    iosBundleId: 'com.example.assignment2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCy5c_ibXGLf_X5dTYfjec-LhMoQecCuwg',
    appId: '1:677990370488:ios:c1d5eec707700a2130b84d',
    messagingSenderId: '677990370488',
    projectId: 'coffee-app-589b0',
    storageBucket: 'coffee-app-589b0.appspot.com',
    iosBundleId: 'com.example.assignment2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhfP-WakfgPwttHN3WLKMu2L3_Tt5B-Sc',
    appId: '1:677990370488:web:72fe1dc905e9790e30b84d',
    messagingSenderId: '677990370488',
    projectId: 'coffee-app-589b0',
    authDomain: 'coffee-app-589b0.firebaseapp.com',
    storageBucket: 'coffee-app-589b0.appspot.com',
  );
}
